### ISSUE TITLE
Enhancement: libxml.mod: Does not expose xmlTextWriterSetIndentString

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#11]
Currently libXML.mod by default saves formatted XML files with double space "  " as indentation. libXML itself contains functionality like xmlwriter.c `xmlTextWriterSetIndentString()` which could get used to manipulate the used indent-string.

**Comment by woollybah** [comment]
Indeed, the whole xmlTextWriter API is not implemented.
