### ISSUE TITLE
bigint.mod incomplete

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#16]
Seems "bigint.mod" is more or less a stub-mod.

Does it miss a local commit from you?

**Comment by woollybah** [comment]
It's currently only used by bah.barcode.
Is it something you'd find useful?

**Comment by GWRon** [comment]
Am not sure, currently searching for something like "mapm.mod" (maybe lighter?) or some kind of module allowing to define desired accuracy - so floating point wont create that much trouble on multiplayer (not hotseat) games.

So when I eg. allow up to 100 million and need 3-4digits accuracy this means I am over uint32 - maybe blitzmax long is 64 bit, so this should be "enough".

**Comment by woollybah** [comment]
Use bah.bsdnt for a fully implemented solution.
