### ISSUE TITLE
BAH.libwebsockets Build Error

### ISSUE THREAD

**Issue by Hezkore** [maxmods/bah.mod#27]
libwebsockets no longer compiles in BMX-NG or Vanilla BMX.

> In file included from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/libwebsockets.h:38:0,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/private-libwebsockets.h:113,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/extension-deflate-frame.c:1:
C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/win32port/win32helpers/websock-w32.h:20:16: error: conflicting types for '_sleep'
 #define usleep _sleep
                ^
In file included from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/private-libwebsockets.h:40:0,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/extension-deflate-frame.c:1:
C:/Program Files/BMX NG/MinGW32/x86_64-w64-mingw32/include/stdlib.h:604:24: note: previous declaration of '_sleep' was here
   _CRTIMP void __cdecl _sleep(unsigned long _Duration) __MINGW_ATTRIB_DEPRECATED;
                        ^
In file included from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/libwebsockets.h:38:0,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/private-libwebsockets.h:113,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/extension.c:1:
C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/win32port/win32helpers/websock-w32.h:20:16: error: conflicting types for '_sleep'
 #define usleep _sleep
                ^
In file included from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/private-libwebsockets.h:40:0,
                 from C:/Program Files/BMX NG/mod/bah.mod/libwebsockets.mod/libwebsockets/lib/extension.c:1:
C:/Program Files/BMX NG/MinGW32/x86_64-w64-mingw32/include/stdlib.h:604:24: note: previous declaration of '_sleep' was here
   _CRTIMP void __cdecl _sleep(unsigned long _Duration) __MINGW_ATTRIB_DEPRECATED;
                        ^

**Comment by woollybah** [comment]
Should compile on Win32 again, with the latest TDM MinGW.
