### ISSUE TITLE
wrong Type returned in TxmlNode::getFirstChild method

### ISSUE THREAD

**Issue by bornd37** [maxmods/bah.mod#32]
First thank you, Brucey, for sharing your libraries with us. They are excellently done.

In the TxmlNode Type the getFirstChild method is returning a TxmlBase type rather than TxmlNode (around line 2075). I changed it to TxmlNode as the line inside shows and it seems to run without issue.

Again thank you for sharing your time and talent!!

**Comment by woollybah** [comment]
Hi!

I believe the code is correct.
A child could be any one of type XML_DOCUMENT_NODE, XML_ATTRIBUTE_NODE, XML_DTD_NODE, XML_ENTITY_DECL, XML_ELEMENT_DECL, XML_ATTRIBUTE_DECL, or a TxmlNode.

TxmlBase is the base type for all of those.

If you know you are expecting a TxmlNode (by default, it is a XML_ELEMENT_NODE), you can cast the result to TxmlNode... for example:
```blitzmax
Local node:TxmlNode = TxmlNode(someNode.getFirstChild())
```

Do you have an example where you feel this should not be the case?

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by bornd37** [comment]
Apologize for not replying earlier.

Thanks for your reply, Brucey. I changed it because of the method itself (which is why the compiler threw an error):

Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	Return TxmlNode(Super.getFirstChild(nodeType))
End Method

As you can see the method definition says it is returning a TxmlBase object, yet the return statement is returning a TxmlNode object. If you want to change it to Return TxmlBase(..) that, to me, is totally your prerogative as your the owner of the library. I changed it to return a TxmlNode because of the return statement.

**Comment by GWRon** [comment]
Think I get what @bornd37 means:

```BlitzMax
Type TxmlBase
	Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
	'returns a TxmlBase
...

Type TxmlNode extends TxmlBase
	Method getFirstChild:TxmlBase(nodeType:Int = XML_ELEMENT_NODE)
		Return TxmlNode(Super.getFirstChild(nodeType))
	End Method
```

See that this tries to return a "TxmlNode" regardless of "nodeType"?
I am not sure, but doesn't this cast to "TxmlNode" destroy a potentially different child (eg a TxmlAttribute) ?

If `TxmlNode.getFirstChild` is only allowed to return `TxmlNode` then you can adjust the return type of this method. But if it is allowed to return everything extending from `TxmlBase` then there is no need to even override `TxmlBase.getFirstChild` from within `TxmlNode`.

**Comment by GWRon** [comment]
Here is an example showing that this "cast-to-TxmlNode" in the overridden method invalidates all other extended-from-TxmlBase-variants.

```BlitzMax
SuperStrict

Framework Brl.StandardIO


Type TBase
	Field child:TBase
	
	Method getFirstChild:TBase()
		return child
	End Method
End Type


Type TExt extends TBase
	Method getFirstChild:TBase()
		return TExt(child)
	End Method
End Type


local b:TBase = new TBase
b.child = new TBase

local e:TExt = new TExt
e.child = new TBase


if b.getFirstChild()
	print "b.child is valid"
else
	print "b.child is invalid"
endif
if e.getFirstChild()
	print "e.child is valid"
else
	print "e.child is invalid"
	if TBase(e.getFirstChild())
		print " ... but e.child is of TBase"
	endif
endif
```

So the current implementation should really be defined as `Method getFirstChild:TxmlNode(nodeType:Int = XML_ELEMENT_NODE)` - or should not cast to `TxmlNode`. If you change the definition, then it is also "clear", that "TmyxmlNode extends TxmlNode" would be a valid return type

**Comment by woollybah** [comment]
Indeed, my mistake. Thanks ;-)

**Comment by GWRon** [comment]
overridden methods not needed ...they return exactly what the super.method returns.
