### ISSUE TITLE
libcurl error on windows - socket.h not available there

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#35]
For details see here:
http://www.blitzmax.com/Community/posts.php?topic=107340#1328750

![](https://s17.postimg.org/5gkwprpdr/libcurl.png)

Problem: Errors out on windows because `sys/socket.h` is not found. Maybe you did not correctly config the library for cross-compilation. I assume on windows you should use `winsock.h` or so

**Comment by woollybah** [comment]
Indeed.
Process generally goes... build and test on OS X. Commit. Build and test on Win32. Commit.
Unfortunately, due to real life intervening, there was a larger time span between the first commit and the second than I'd normally expect.
