### ISSUE TITLE
Compiler issue with latest libcurl.mod

### ISSUE THREAD

**Issue by GrisuBMX** [maxmods/bah.mod#44]
Hi Brucey!

Your latest update seems to miss a file:

"In file included from C:/BlitzMax/mod/bah.mod/libcurl.mod/src/lib/amigaos.c:23:0:
C:/BlitzMax/mod/bah.mod/libcurl.mod/src/lib/curl_setup.h:639:12: fatal error: mbedtls/md4.h: No such file or directory
 #  include <mbedtls/md4.h>
            ^~~~~~~~~~~~~~~
compilation terminated.
Build Error: failed to compile C:/BlitzMax/mod/bah.mod/libcurl.mod/src/lib/amigaos.c
Process complete"

Grisu

P.S. I'm on BMX vanilla with GC 7.1.

**Comment by woollybah** [comment]
Hi. I have BlitzMax 1.50 (with bmk 3.18 and gcc 7.0) and NG (with bmk 3.21 and gcc 7.2), on Windows 10 Pro, and it builds fine :
```
bmk makemods -a -r bah.libcurl
```

Maybe check that you have bah.mbedtls there?
My 1.50 bah.mod was just checked out in a clean install, and everything appears to be in git.

**Comment by GrisuBMX** [comment]
Hello,

thanks for helping me out.. again. 
Added your "libssh2.mod" and "mbedtls.mod" and all runs fine. 

Btw: Is there a safe value for the maximum amount of threads / server connections at one time?

**Comment by woollybah** [comment]
It's probably not something you need to worry about too much? Just don't go creating hundreds of them ;-)
You might find that your network connection is the bottleneck that will determine the value that works best.
