### ISSUE TITLE
BaH libcurl: Lost WinXP compatibility

### ISSUE THREAD

**Issue by GrisuBMX** [maxmods/bah.mod#45]
Hello,

since the last update I get user reports that a compiled exe can no longer be started under Windows XP due to an older version of "msvcrt.dll".

Error message given: 
"The procedure entry point _vsnprintf_s could not be located in the dynamic link library msvcrt.dll."

Is there a way to include some workaround for the latest module changes. so that older Windows versions are still supported? 
Or create some "classic module" that uses the older library to keep the compatibility? Compiler switch for that should be something like "gcc -specs=msvcr80 -o foo foo.c" from my google search.

P.S.: On top of that my prp.exe gained around 800 KB of weight just from the module update. That's a bit much. 

Grisu

**Comment by GWRon** [comment]
Filesize increase might be because of the replacement of openssl with mbed tsl.

Can't you meanwhile just use a bah.libcurl revision before that commit updating it?

**Comment by woollybah** [comment]
I've updated (and patched - ARMmbed/mbedtls#355 ) mbedtls, which should hopefully solve your link issue on old Windows.

If exe size is a problem, you can always push it through [UPX](https://upx.github.io/) as part of your build/release process.

Or revert to a previous version of bah.libcurl, as @GWRon mentions....

**Comment by GrisuBMX** [comment]
Yes, I already created a backup folder for such future issues.

I just send out a new PRP build with the latest updates to several Win XP users. Hopefully I'll get back positive reports soon. Sadly, I don't have a Windows XP machine myself anymore.

Thanks a lot for digging into this Brucey. Thanks for the assistance GWRon.

**Comment by GrisuBMX** [comment]
First feedback indicates that the issue is fixed. Closing thread. :)
