### ISSUE TITLE
Update persistence.mod to handle TStringMap, TIntMap, ...

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#46]
Persistence.mod contains a special handling for "TMap" - which is surely needed for "TStringMap" and the other new map types too.

Also the object storage itself could get replaced by TStringMap.

**Comment by GWRon** [comment]
Or do they not have this "nil" part to get handled?

**Comment by woollybah** [comment]
In theory the new version will handle these, given a custom serializer for each... Maybe we need a new persistence module that implements some of these...

**Comment by GWRon** [comment]
If you intend to create them - think of the question I put under the "custom serialiser"-commit. Thinking of the JSON-Persistence.mod.
Would be a shame if you need to write the custom serializer for each variant - instead of some "format agnostic" variant. Regarding "bmo <= 5" in the tmap-serializer there seem to be direct connections to "reading from XML" which could be something problematic.
