### ISSUE TITLE
Implement custom serializer/deserializer.

### ISSUE THREAD

**Issue by woollybah** [maxmods/bah.mod#47]
Currently bah.persistence is not flexible when it comes to processing "custom" types - especially those for which the data is not stored directly in fields.

We should extend the persistence modules with the concept of a serializer or deserializer - extra functionality which can be "plugged" into the persistence module at some later point, much in the same way as image loaders work.

It would be preferred to use interfaces as we could have interfaces for both serializer and deserializer, but unfortunately this probably wants to be compatible with legacy code, in which case the base class will have to handle both...

Sub-classes will extend from the base class.

Either the persistence module will require them to register directly with a persistence instance, or something more general

Type ids will be used to map objects to the correct serializer.
Serializers themselves could determine what fields to persist, or perform other conversions as required.

**Comment by GWRon** [comment]
Maybe you could check out this:
https://github.com/TVTower/TVTower/blob/master/source/Dig/external/persistence.mod/persistence.bmx

I extended TPersistence to allow hooking in a generalized "serializer". This is a class/type handling the serialization/deserialization "on top of everything".
I also added a check if a type exposed a serialization/deserialization method.

Priority is:
- if a serializer is set, and the serializer has "SerializeTMapToString()" and "DeserializeTMapFromString()" defined, then this is called.
- if the class itself had the above named methods, they are called
- if both above are not available, do the default "field by field" serialization

Why in this priority? Sometimes you do not want to alter sourcecode (eg. module code) so you cannot extend "TMap" to have "SerializeTMapToString()". But you can write your own serializer, handling the TMap serialization for you - without needing to alter the TPersistence.mod code.

**Comment by woollybah** [comment]
I don't like adding methods to things that shouldn't know about stuff :-p

well, this is what I have so far. There are a couple of new types. A builder, and our serializer base...
```blitzmax
Type TXMLPersistenceBuilder

	Field serializers:TMap = New TMap
	
	Method New()
		Register(New TMapXMLSerializer)
	End Method

	Method Build:TPersist()
		Local persist:TPersist = New TPersist
		
		For Local s:TXMLSerializer = EachIn serializers
			persist.AddSerializer(s)
		Next
		
		Return persist
	End Method
	
	Method Register:TXMLPersistenceBuilder(serializer:TXMLSerializer)
		serializers.Insert(serializer.TypeId(), serializer)
	End Method

End Type


Type TXMLSerializer
	Field persist:TPersist

	Method TypeId:String() Abstract
	Method Serialize(tid:TTypeId, obj:Object, node:TxmlNode) Abstract
	Method Deserialize() Abstract
	
	Method SerializeFields(tid:TTypeId, obj:Object, node:TxmlNode)
		persist.SerializeFields(tid, obj, node)
	End Method
	
	Method Contains:Int(ref:String, obj:Object)
		Return persist.Contains(ref, obj)
	End Method
	
	Method AddObjectRef(ref:String, obj:Object)
		persist.objectMap.Insert(ref, obj)
	End Method
	
End Type
```
Basic usage :
```blitzmax
Local persist:TPersist = New TXMLPersistenceBuilder.Build()
```
But you can chain together Register() calls as you need...

The TMap serializer it added by default. If you choose to, you can use your own instead, simply by registering it before you build the TPersist instance.

This is the TMap serializer :
```blitzmax
Type TMapXMLSerializer Extends TXMLSerializer

	Method TypeId:String()
		Return "TMap"
	End Method
	
	Method Serialize(tid:TTypeId, obj:Object, node:TxmlNode)
		Local ref:String = TPersist.GetObjRef(New TMap._root)
		If Not Contains(ref, New TMap._root) Then
			node.setAttribute("nil", ref)
			AddObjectRef(ref, New TMap._root)
		End If

		SerializeFields(tid, obj, node)
	End Method
	
	Method Deserialize()
	End Method

End Type
```
I've yet to implement deserializing, but expect it will be much the same.
I may refactor more as I go....

**Comment by GWRon** [comment]
I thought about a similar thing (registering serializers to the base class).

Hope the refactoring isn't too complex at the end - will have to re-add the fixes I needed for grable's reflection stuff (null-array identification was different to vanilla and ng-brl.reflection  null-array identification).

@ Registering Serializers
Maybe add some kind of "defaultSerializers" so you only need to add them "once" for the whole project, or allow setting them as group or so.
Else the item kicking of the serialization needs to know about what types might be needed - while it would be better if a type can register itself for "am ready for serialization" without the main file needing to know about it. Similar to the graphics drivers registering to the base driver.

In our case the TMap could implement that serializer stuff and it won't be needed to get manually added to TPersist. Of course this is not preferrable for basic modules - except it would be some generic "serialize/deserialize" function (like other languages implement too) .

**Comment by woollybah** [comment]
Okay, that's done, I hope...  let me know if you have any problems with it ;-)
