### ISSUE TITLE
Cairo.mod not compiling: missing pixman.h

### ISSUE THREAD

**Issue by jpakkanen** [maxmods/bah.mod#48]
I'm trying to compile the latest Cairo on Windows 10, but the source package is missing some headers.

**Comment by woollybah** [comment]
Hi there!
What version of BlitzMax/bmk/modules are you using?

I just tested with BlitzMax 1.50 - bmk(ng) and my updated brl/pub modules, and BlitzMax NG, and it compiled and ran some examples as expected...

**Comment by jpakkanen** [comment]
Brucey,

That was it, thanks! I updated to the latest BMK NG and now it works.
