### ISSUE TITLE
bah.random crash (EXCEPTION_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by jpakkanen** [maxmods/bah.mod#49]
Brucey,

I'm getting back to coding my old project where I've been using your random mod to generate pseudo random numbers. I've recently updated bah.random to the latest version (along with bmx ng, mod.brl and mod.pub) and it seems bah.random is now suddenly very unstable in my Windows 10 environment. 

What I'm doing is that I'm re-seeding the generator many times in a row with a number that has been procedurally generated elsewhere (this needs to happen for me to get enough variance in my results). It seems to be the act of rapid reseeding that crashes the Mersenne twister.

Here's a quick demo that crashes on my system every time it's run:

SuperStrict
Framework bah.random

For Local i:Long = 1 To 200000
   SeedRnd(i)
   DebugLog(Rnd(-2,2))
Next

If I seed the twister only once prior the for loop, it works. But seeding it in a loop seems to bring it to its knees. This exact use case has worked perfectly with an older version of the bah.random mod, so it seems to have regressed since the last time I've used it. 

My workaround is to revert back to some bit shifting techniques to give me some pseudo randomness, but in my use case it starts to repeat itself quite rapidly and is not nearly as fast solution as your random mod.

Any help is appreciated :)

**Comment by woollybah** [comment]
Your example does indeed crash.

However, if you use Print instead of DebugLog it works - so I think there may be an issue with the Debug stuff.

Can you confirm, please? Thanks :-)

**Comment by jpakkanen** [comment]
Hmm, this example indeed seems to work without using debuglog. However, when it crashes with DebugLog the stack trace points to random.bmx's line: "Return bmx_genrand_res53(sfmtPtr)"

If I use the Blitz's stock Rnd functions, both my game and this example works with or without DebugLog.

Also, I'm not using DebugLog at all in my game, but still it crashes there, with the exact same stacktrace result. Perhaps using DebugLog in this example is one of the many ways which happens to manifest this bah.random bug?

**Comment by GWRon** [comment]
Without looking into it in detail: didn't we have some trouble with the GC kicking in too early sometimes, so things got freed while they were needed? Maybe this is something similar.

**Comment by woollybah** [comment]
Thanks. I'll have a deeper dig into it. I may have done something wrong in the wrapper.

**Comment by GWRon** [comment]
@jpakkanen 
If you insist on Mersenne Twister (PRNG) you might have a look at
https://github.com/GWRon/Dig/blob/master/base.util.mersenne.bmx
but it does only allow one single generator at the same time (sometimes one needs more - to make certain things replicateable regardless of also replicateable other inputs - enemy spawns vs AI thinking)

**Comment by jpakkanen** [comment]
@GWRon, thanks, looks like this might work. What I need is a fast way to generate procedural randomness which is consistent across systems and platforms. 

However, in my game I have the need to get some 64 bit long integers (physics simulation with planetary masses in kilograms), but your Twister seems to provide only 32 bit ones out of the box. I don't need the Int64 granularity, though, so I can get them converted to 64-bit longs by using multipliers.

I'll give it a shot, thanks!

**Comment by GWRon** [comment]
I would wait for Brucey - but if he cannot come up with a solution (I reaaaallly doubt that ;-)) I just wanted to make you aware of its existence.

Couldn't you go back to the older bah.random in the meantime?

**Comment by jpakkanen** [comment]
Yeah, I have always had 100% faith on Brucey :) 

Original bah.random doesn't provide 64 bit integers either, which currently results in some of my random planets to have negative gravity. Well I guess there's some fun in that, too!

**Comment by jpakkanen** [comment]
Ah, you said old _bah.random_, but I thought you said old _brl.random, which would be a workaround right now as my game is not yet that far that non-pseudo randomness would cause problems.

I suspect that using old _bah.random_ would not be ng compatible, judging from the commit messages. I would have to revert back to the stone ages with bmx and all of the other modules as well. I think I'll wait for Brucey.

**Comment by woollybah** [comment]
Hi. Let me know if that sorts it out.

I had been creating an instance of the sfmt struct with malloc, but it didn't seem to like it, for some reason. So I've refactored things a bit... it seems much more stable for me now, and runs without crashing in debug...

**Comment by GWRon** [comment]
So bah.random now is using only a single fmt-instance? Would have liked to see a way to use multiple PRNG generators (of course the current "convenience functions" would use a default generator - while some new functions would offer an parameter to specify which fmt-instance to use).

**Comment by jpakkanen** [comment]
Hi,

Thanks Bruce, but I'm still getting access violations. Only this time I started to get them at SeedRnd() and not Rnd() anymore.

I noticed that very minor changes to the code (like changing a Long datatype into an Int) make the fmt crash at different phases of execution. At other times the program might be able to call SeedRnd() + Rnd() combos many times, and when I change some entirely unrelated part of the code just a tiny bit, it would start to always crash at the very first SeedRnd() call.

For example, my above sample code works if I change the Long variable 'i' to an Integer, but crashes when I call SeedRnd with a long int parameter. I can see the wrapper's SeedRnd() method casts the value into an int before passing it over to the fmt engine, but for some reason it seems to make a difference.

Sounds like there is something funny going on in the memory space, probably not related to bah.random but maybe type casting in general?

**Comment by woollybah** [comment]
Thanks for the information. I'll have another stab at it...
Are you doing any threaded work in your app?

**Comment by jpakkanen** [comment]
Thanks Brucey,

No, I'm not using multithreading.

**Comment by woollybah** [comment]
I've just pushed another commit... if you'd like to try it.
Your example ran fine, even with millions of generations.

I've refactored everything to run off a TRandom type. There's a global one for the standard functions, but feel free to use your own instance too - in theory you can have several generating using different seeds, at the same time.
The other major change was to align the pointer to 16 bytes - which may have been the main cause - SSE is not happy if its data is not on 16-byte boundaries.

However, if it still crashes (you'd think I'd be able to write some code that didn't crash when calling 5 functions!)... the only other option I can think of, is to disable SSE in the CC_OPTS. But it would be nice if we could have them, as it makes things faster...

Please let me know how you get on anyway! Thanks!

**Comment by jpakkanen** [comment]
Thank you, Brucey! It seems to be working now in all of the cases I've tried it with. So far so good :)

👍

**Comment by woollybah** [comment]
Phew! Got there in the end then!

I'll leave this open for now, just in case...
