### ISSUE TITLE
Persistence: Issues

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#51]
I tried to use the new persistence type (+ serializers) for my savegames. I added back some custom fields so that it stays compatible (albeit the fields are not used in the persistence code..). Added "nosave" to the metatag checks next to "nopersist" (compatibility). 

It saved my game (but loading fails with some "mismatch" lines)
```
Opening and ending tag mismatch: bmo line 2 and field
File:  . Line:1812 Column:13

Extra content at the end of the document
File:  . Line:1813 Column:5
Segmentation fault
```

The lines are:
```XML
1811:      </TAchievementCollection>
1812:    </field>
1813:    <field name="_adAgencySortMode" type="int">0</field>
```
so it blames the "<" of `</field>` as if it was in some "read string mode" or so ?

PS: you could do a 
persist:TPersist = new TPersist
and serialize from there without any clue about "serializers". How to enforce the usage of the TXMLPersistenceBuilder? Or at least "inform" the developer about the maybe "wrong usage" ?

**Comment by woollybah** [comment]
Can you send me a broken example please? Thanks :-)

**Comment by GWRon** [comment]
Send you a 7z of the quicksave file by mail. It also includes instructions if you want to use it within the game itself - ignore them - I meanwhile pushed the temporary changes to a new branch so you should be able to check them out more easily:

https://github.com/TVTower/TVTower/commits/test_newpersistence

**Comment by woollybah** [comment]
Are you happy with this now, or do you still think there are issues with it?
