### ISSUE TITLE
libXML:fails to build on 64 bit NG

### ISSUE THREAD

**Issue by noroads2015** [maxmods/bah.mod#57]
32 bit compiles fine.  64 bit gives these errors
`[100%] Linking:.keyword.debug.exe
C:/BlitzMax/mod/bah.mod/libxml.mod/libxml.debug.win32.x64.a(glue.cpp.debug.win32.x64.o): In function `bbStringFromXmlChar':
C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: undefined reference to `__imp_xmlFree'
C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: undefined reference to `__imp_xmlFree'
C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: undefined reference to `__imp_xmlFree'
C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: undefined reference to `__imp_xmlFree'
C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: undefined reference to `__imp_xmlFree'
C:/BlitzMax/mod/bah.mod/libxml.mod/libxml.debug.win32.x64.a(glue.cpp.debug.win32.x64.o):C:/BlitzMax/mod/bah.mod/libxml.mod/glue.cpp:403: more undefined references to `__imp_xmlFree' follow
collect2.exe: error: ld returned 1 exit status
Build Error: Failed to link C:/BlitzMax/mod/bah.mod/libxml.mod/doc/.keyword.debug.exe
Process complete
`

**Comment by woollybah** [comment]
Hi, can you please provide details of the version of MinGW you're using, and that of bah.libxml and bcc please?

I'm using MinGW-w64, gcc 7.2, with bah.libxml 2.02, and the latest bcc, and it's working as expected.

You may want to try rebuilding it. From the command prompt in the BlitzMax/bin folder you can do :
```
bmk makemods -a -r -g x64 bah.libxml
```

**Comment by noroads2015** [comment]
rebuilding the module seems to have solved it.
