### ISSUE TITLE
serial.mod: no data received

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#64]
I have a device connected via USB/virtual-com-port.

The device port is listed and I can "open" it. Yet "available()" never returns > 0.

I have a similar application in Java - which opens the port with the same configuration (9600 baud, eightbits, parity_none, stopbits_one, ...) and it can read values as it should.

**Comment by GWRon** [comment]
Happens in vanilla too (just to sweep away a potential source of the issue).

**Comment by GWRon** [comment]
Using some "vanilla blitzmax examples" (using Win32 api) it works. So it must be something in the module.

**Comment by woollybah** [comment]
I've updated to the latest version, and applied a PR which sets some more initial values on win32.
Please let me know if that makes a difference :-)

**Comment by woollybah** [comment]
bump

**Comment by GWRon** [comment]
Still was not able to test it properly (no access to the computer+device yet). Am still aware of this issue report here.

**Comment by GWRon** [comment]
Today I have access to the device again ... but ... oddly even the other code (using windows api commands) does just return empty strings for now. The java app properly connects and is able to send and receive commands.
The updated serial.mod returns empty strings too - so I for now cannot say if it is working - or not. And I have no clue why the old variant should no longer work. If it was an OS update then I assumed it might bork up the java implementation too but as this one works...

**Comment by GWRon** [comment]
A backup'd variant of the program still works... so maybe a BCC/BMK-update made stuff not work anymore (think I had some issues with NG and "TBank" not getting filled properly ...)

**Comment by woollybah** [comment]
Can you confirm that the changes made to this module solved the "available" issue you were originally having?

**Comment by GWRon** [comment]
Yes - with the old brl.mod and the new serial.mod I had successful communication between my program and the serial attached device.

But as I am not sure if this is still somehow correlated - I left it up to to you to close this issue here.

**Comment by GWRon** [comment]
Latest brl.mod (with "timer fix") does still result in "empty strings". So same issue as before.

**Comment by GWRon** [comment]
Using latest brl.mod (timer...) and latest bah.mod (serial...) I do not receive strings while my java reference app still is able to do so.

**Comment by GWRon** [comment]
Just tried in on my linux notebook and there it did not receive any string too.

**Comment by GWRon** [comment]
Seems I was able to send my previous message before this one ;-)
![fromthepast](https://user-images.githubusercontent.com/2625226/51177760-d6520e00-18c0-11e9-8ee0-cd5a1b55a528.png)


OK, so as it fails on Linux (and on another computer) too i think it is either the library+bmx or the device (which works with java). I was not able to compile the original example provided by the "serial library" - compiled sources and tried to compile example but it failed with some functions not being known to the example code - so I might have done it incorrectly.
- installed dependencies
- make
- make install
  -> this copied stuff to "/tmp/usr/..." instead of "/usr"
  -> copied that files manually
- compiled the example code but that failed then with some "serial:bla" not found (the enumerate function and some more stuff)

"bah.serial.mod" instead was outputting the desired device uri - I then pasted that into the read-example, compiled that and run it via "sudo" as it needed permissions to read from that device (and sudo was the most easiest way to test it out without playing with ACLs).

**Comment by GWRon** [comment]
I tried an external terminal for rs322 communication and was not able to receive data too. So there is the big question left open: why does it work in the java application? what is done different there?

Also meanwhile the chip on the device changed compared to the device when it worked some weeks ago (do not ask ...). So there might be issues connected to that change too (albeit still... "why does it work with java?").

**Comment by GWRon** [comment]
So firmware was updated and the dev used "/" instead of a newline. Does not explain everything but at least serial.mod is reading data now.

Using it in a DLL leads to a EAV though.
