### ISSUE TITLE
TPersistence.mod: use mxml instead of libxml?

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#67]
Could TPersistence get rewritten to use the new brl.xml instead of libxml (aka removing a "dependency") ?

Or would it be better to replace the whole TPersistence with a TSerialization module utilizing either json or mxml (means it needed another "storage" wrapper which can use json or xml or ...)

**Comment by GWRon** [comment]
The "storage wrapper/driver" sounds interesting. Let me explain why:
If we added a "stub" storage we could add (de-)serialisation to "brl.blitz". So each simple application can use it without adding the dependency of "libxml" (or json). Maybe one prefers to simply output stuff to an (properly escaped) string of values ...


Regarding "Serialization" and "Persistence" - it should be made clear wordwise, that it does not do a memory dump and some things might not be preserved during persisting/serialization. Talking about "TGLImageFrame" or other driver dependend stuff. So OpenGL information is not preserveable in all cases - or it is "[graphics] context" dependend.

**Comment by woollybah** [comment]
I expect the version of persistence to find its way into brl will use brl.xml instead.
