### ISSUE TITLE
TPersistence.mod serializes an item twice

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#69]
I tried to serialize a `TLowerString` with a custom serializer:

```BlitzMax

Type TLowerStringXMLSerializer Extends TXMLSerializer

	Method TypeName:String()
		Return "TLowerString"
	End Method

	Method Serialize(tid:TTypeId, obj:Object, node:TxmlNode)
		Local ls:TLowerString = TLowerString(obj)
		SerializeObject(ls.orig, node.AddChild("orig"))
	End Method


	Method Deserialize:Object(objType:TTypeId, node:TxmlNode)
		'use CreateObjectInstance() to keep reference
		local ls:TLowerString = TLowerString(CreateObjectInstance(objType, node))
		if ls
			for local childNode:TxmlNode = EachIn node.GetChildren()
				if childNode.GetName() = "orig"
					local value:object = DeserializeObject(childNode)
					if ls then ls.DeSerializeTLowerStringFromString( string(value) )
					return ls
				endif
			Next
		endif
		Return ls
	End Method

End Type
TXMLPersistenceBuilder.RegisterDefault(New TLowerStringXMLSerializer)
```
Maybe this is already not correct ... we'll see.

Within TPersistence's method `SerializeObject:TxmlNode(obj:Object, parent:TxmlNode = Null)` there is no check to skip serialization if it was already done. ObjRef is fetched and inserted again (overriding potentially existing ones with that key - this is OK).
Then the serializer for "TLowerString" is called ignoring an earlier run serialization.

Therefor I extended a bit of code there to check if the object was serialized already:
```BlitzMax
			Local objRef:String = GetObjRef(obj)

			node.setAttribute("ref", objRef)

			'RONNY
			'already serialized before
			If Contains(objRef, obj)
				return node
			endif

			AddObjectRef(obj, node)

			' We need to handle array objects differently..
			If objectIsArray Then
```
Is this correct or did I miss something in the logic and it works different to what I assumed?

**Comment by GWRon** [comment]
I just debug printed if it skips something now - and with that information I saw that it does not only happen to my custom serialized stuff but to way more items - maybe it's a flaw in the map-serializer?

**Comment by GWRon** [comment]
Ok, redid the serializer in a little code-sample and I think this does a better job:
```BlitzMax
Type TLowerStringXMLSerializer Extends TXMLSerializer

	Method TypeName:String()
		Return "TLowerString"
	End Method

	Method Serialize(tid:TTypeId, obj:Object, node:TxmlNode)
		Local ls:TLowerString = TLowerString(obj)
		node.SetContent(ls.orig)
	End Method


	Method Deserialize:Object(objType:TTypeId, node:TxmlNode)
		'use CreateObjectInstance() to keep reference
		local ls:TLowerString = TLowerString(CreateObjectInstance(objType, node))
		if not ls then return null

		'mark processed
		AddObjectRef(node.GetAttribute("ref"), ls)
		'recreate lower string interna without creating a new instance
		ls.DeSerializeTLowerStringFromString( node.GetContent() )

		Return ls
	End Method

End Type
TXMLPersistenceBuilder.RegisterDefault(New TLowerStringXMLSerializer)
```
But as said this is for another issue.

**Comment by GWRon** [comment]
After circumventing https://github.com/bmx-ng/bmx-ng/issues/54 (evaluating function calls in function params from "right to left" instead of "left to right") by fetching the results of the deserialized node contents of a "TMap" first before adding them I got my savegame to load.

but it fails if I skip serialization of stuff serialized before. Means somehow stuff gets marked as "serialized" (objRef is stored already) while it wasn't. Because with the "skip" some data is missing. 

Means I still miss some steps to properly "fix" the issue.

**Comment by woollybah** [comment]
I'm working on changes to the module - and adding some unit tests too, which will hopefully help.

**Comment by GWRon** [comment]
I already was investigating the serializer-implementations and what types they use.

Eg. I have an object having a field "room:TRoomBase". In the serialization the object "building:TRoom" is stored there and properly serialized. Then I have a collection with a "TList" (remember, has its own serializer). They serialize that "building:TRoom" properly as "<TRoom ...".

If I do not add the "skip" (checkContains) then it receives a full serialization in that node. During Deserialization it works as expected (as it surely just "overrides" the already deserialized one).

Now I added this "skip" and the "<TRoom" node just contains the type-name and the "ref". So far so good. But during deserialization it somehow skips to restore the content there - and upcoming code in the game can no longer find the object.


Maybe that helps "seeing the issue".


@ unit tests
I thought so already when seeing your commit to maxunit.

**Comment by GWRon** [comment]
Whil you change the module I am checking stuff a bit here and there:

As described the list contains now elements like this:
```XML
            <TRoom ref="J50FC"/>
            <TRoom ref="J5094">
              <field name="id" type="int">74</field>
```
The list (de-)serializer calls "DeserializeObject()" for each entry. Leading to "DeserializeByType()".
"DeserializeByType()" tries to find a custom serializer - and if none was found it calls "DeserializeFields()".
"DeserializeFields()" does nothing if the node does not contain children. As you see above, `<TRoom ref="J50FC"/>` does not contain children.

One of these functions needs to take care of that "ref" information but no children (or "value" attributeś or so). So if eg. the 'node.GetChildren().count() = 0` then it should try to find the refObject behind the stored  `ref`.
