### ISSUE TITLE
Persistence.mod not compiling under x86

### ISSUE THREAD

**Issue by xlsior75** [maxmods/bah.mod#72]
Latest version of bah.mod/Persistence.mod is not compiling under x86 release or debug (gcc 8.1.0), x64 appears OK.

`
Building x86 Release
[  7%] Processing:persistence.bmx
[  7%] Processing:common.bmx
Compile Error: Unable to find overload for base36(Long). Argument #1 is "Long" but declaration is "Int".
[c:/code/BlitzmaxNG810/mod/bah.mod/persistence.mod/persistence.bmx;91;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/bah.mod/persistence.mod/persistence.bmx

Building x86 Debug
[  7%] Processing:persistence.bmx
[  7%] Processing:common.bmx
Compile Error: Unable to find overload for base36(Long). Argument #1 is "Long" but declaration is "Int".
[c:/code/BlitzmaxNG810/mod/bah.mod/persistence.mod/persistence.bmx;91;0]
Build Error: failed to compile (-1) c:/code/BlitzmaxNG810/mod/bah.mod/persistence.mod/persistence.bmx`

**Comment by GWRon** [comment]
@xlsior75 
Are you using Persistence.mod in projects? Did you encounter any other issues?

If you use it:
What would you like to see in Persistence.mod too?
Would you like such a thing to be "inbuilt" (basic module) ?
Is it flexible enough?
