### ISSUE TITLE
[sstream.mod] "common[_NG].bmx" not existing

### ISSUE THREAD

**Issue by GWRon** [maxmods/bah.mod#78]
As written in this thread:
https://www.syntaxbomb.com/index.php/topic,5613.new.html#new

the file sstream.bmx tries to import "common.bmx" respective "common_NG.bmx". Bot files are not present in the directory.

**Comment by GWRon** [comment]
Couldn't this module get interlaced into the existing brl.stream? I mean so that brl.stream supports large files - and stuff extending TStream can use it too? Or would that mean a multitude of needed adjustments?

**Comment by woollybah** [comment]
brl.stream (in NG) already supports large files.

**Comment by GWRon** [comment]
Maybe add a little sidenote to the module's readme.md so people are aware of it being only useful for "vanilla".
