### ISSUE TITLE
[ng] Problem building bah.box2d

### ISSUE THREAD

**Issue by woollybah** [maxmods/bah.mod#8]
bah.box2d doesn't currently build with bmx-ng.

**Comment by GWRon** [comment]
It builds (in the sense of compiling) now if you:

- open up "common.bmx"
- replace `Function bmx_b2abb_isvalid(handle:Byte Ptr)` with ``Function bmx_b2abb_isvalid:int(handle:Byte Ptr)`

but examples are still failing: 
```
Building test
[ 99%] Processing:test.bmx
[ 99%] Compiling:test.bmx.console.release.linux.x86.c
[100%] Linking:test
/BlitzMaxNG/mod/bah.mod/box2d.mod/examples/.bmx/test.bmx.console.release.linux.x86.o: In function `__m_test_Test_MouseUp':
test.bmx.console.release.linux.x86.c:(.text+0x13f): undefined reference to `bah_box2d_b2Joint'
/BlitzMaxNG/mod/bah.mod/box2d.mod/examples/.bmx/test.bmx.console.release.linux.x86.o: In function `__m_test_DestructionListener_SayGoodbyeJoint':
test.bmx.console.release.linux.x86.c:(.text+0x17d): undefined reference to `bah_box2d_b2Joint'

[...]
```

**Comment by GWRon** [comment]
What I also do not understand (unknown feature for me..) is this:

samples import test.bmx
test.bmx imports render.bmx
render.bmx just imports `BRL.GLMax2D` and nothing else

But within that file render.bmx the type is extended from something defined in the box2d.mod : `Type debugDraw Extends b2DebugDraw`.

Again: Box2D.mod is only imported via the sample files. So this means:
sample imports the Box2D.mod and "test.bmx"
test.bmx imports render.bmx
render.bmx accesses things defined within Box2D.mod

This is... I do not know how to express, but shouldn't an __imported__ file be theoretically be "compileable" - contrary to __included__ files

**Comment by woollybah** [comment]
Fixed.
