### ISSUE TITLE
bah.speech

### ISSUE THREAD

**Issue by nikikust** [maxmods/bah.mod#83]
When I run: speech.speak("hello") -> raise EXCEPTION_ACCESS_VIOLATION

**Comment by GWRon** [comment]
And when doing a debug build?

**Comment by nikikust** [comment]
Yes :(

**Comment by nikikust** [comment]
![EAV](https://user-images.githubusercontent.com/52621231/61611730-3dcc8a00-ac65-11e9-8f71-ea7f38bfacb5.PNG)

**Comment by GWRon** [comment]
Did you install the festival libraries?
The source files do not contain information about dependencies but @woollybah might jump in to say what is required on Windows platforms.

If it "EAVs" in debug mode then most probably something in the "glue/wrapper" (c -> blitzmax -> c) is incorrect.

**Comment by nikikust** [comment]
what do you mean under "festival libraries"?

**Comment by GWRon** [comment]
I assume this is needed: https://github.com/festvox/festival

**Comment by nikikust** [comment]
wow, where will that place in BM dir?

**Comment by woollybah** [comment]
Sorry for the delay in fixing the issue.

**Comment by nikikust** [comment]
Yes, thank you :)
