### ISSUE TITLE
FreeImage fails to compile on BlitzMaxNG MacOS

### ISSUE THREAD

**Issue by peterigz** [maxmods/bah.mod#84]
Hello, I'm getting the following error with both the latest versions of FreeImage and NG (downloaded from blitzmax.org):

```
/Users/peterrigby/Downloads/BlitzMaxNGLatest/mod/bah.mod/freeimage.mod/src/FreeImage/PluginBMP.cpp:1443:14: error: use of
      undeclared identifier 'bpp'
                } else if (bpp == 24) {
                           ^
/Users/peterrigby/Downloads/BlitzMaxNGLatest/mod/bah.mod/freeimage.mod/src/FreeImage/PluginBMP.cpp:1464:14: error: use of
      undeclared identifier 'bpp'
                } else if (bpp == 32) {
```

It does this on both Mojave and now Catalina which I just upgraded to.

**Comment by barracuda156** [comment]
@woollybah Have you been able to compile the whole thing? You commit fixes the first error, but then it still fails almost immediately on:
```
PluginDDS.cpp:359:39: error: 'DDSURFACEDESC2' {aka 'struct tagDDSURFACEDESC2'} has no member named 'ddpfPixelFormat'
```
Etc., then:
```
ImathVec.h:228:41: error: ISO C++17 does not allow dynamic exception specifications
```
Etc.

**Comment by ryandesign** [comment]
Should this one remaining occurrence of `bpp` have been replaced with `dst_bpp` as well?

https://github.com/maxmods/bah.mod/blob/6b7b7cb2565820c287eaff049071dba8588b70f7/freeimage.mod/src/FreeImage/PluginBMP.cpp#LL1422C14-L1422C17

**Comment by ryandesign** [comment]
Should this entire upstream commit have been applied?

https://sourceforge.net/p/freeimage/svn/1809/
